version: '3'

services:


  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - 15432:5432
    volumes:
      - /home/omega/postgres:/var/lib/postgresql/data 
    networks:
      - omega-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "postgres@email.com.br"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 16543:80
    depends_on:
      - postgres
    networks:
      - omega-network

networks: 
    omega-network:
        driver: bridge